- name: Create a file on raspberry pi
  hosts: raspberrypi
  tasks:
    - name: Create a file
      ansible.builtin.copy:
        content: "Hello World"
        dest: ~/Desktop/hello.txt
        mode: "0644"
